# This file generates the GitHub Actions matrix
---
include:
  # totem left (peripheral)
  - board: xiao_ble
    shield: totem_left
    artifact-name: totem_peripheral_left

  # totem right (peripheral)
  - board: xiao_ble
    shield: totem_right
    artifact-name: totem_peripheral_right

  # totem dongle (central)
  - board: xiao_ble
    shield: totem_dongle
    artifact-name: totem_central_dongle

  # reset
  - board: xiao_ble
    shield: settings_reset
