include:
  # totem dongle (central)
  - board: xiao_ble/nrf52840/zmk
    shield: totem_dongle
    artifact-name: totem_central_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y

  # totem left (peripheral)
  - board:xiao_ble/nrf52840/zmk
    shield: totem_left
    artifact-name: totem_peripheral_left

  # totem right (peripheral)
  - board: xiao_ble/nrf52840/zmk
    shield: totem_right
    artifact-name: totem_peripheral_right

  # reset
  - board: xiao_ble/nrf52840/zmk
    shield: settings_reset
