include:
  # Thorium34: the left half is the split central
  - board: xiao_ble/nrf52840/zmk
    shield: thorium34_left
    artifact-name: thorium34_central_left

  - board: xiao_ble/nrf52840/zmk
    shield: thorium34_right
    artifact-name: thorium34_peripheral_right

  # totem dongle (central)
  - board: xiao_ble/nrf52840/zmk
    shield: totem_dongle
    artifact-name: totem_central_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y

  # totem left (peripheral)
  - board: xiao_ble/nrf52840/zmk
    shield: totem_left
    artifact-name: totem_peripheral_left

  # totem right (peripheral)
  - board: xiao_ble/nrf52840/zmk
    shield: totem_right
    artifact-name: totem_peripheral_right

  # reset
  - board: xiao_ble/nrf52840/zmk
    shield: settings_reset
    artifact-name: totem_settings_reset
