manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: caksoylar
      url-base: https://github.com/caksoylar

  projects:
    # ZMK 本体（v0.3）
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml

    - name: zmk-smart-toggle
      remote: caksoylar
      revision: v0.3

    # RGBLED widget（今回追加）
    - name: zmk-rgbled-widget
      url: https://github.com/t-ogura/zmk-rgbled-widget
      revision: main

  self:
    path: config
