manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: caksoylar
      url-base: https://github.com/caksoylar

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml

    # ZMK modules
    - name: zmk-smart-toggle
      remote: caksoylar
      revision: v0.3

    - name: zmk
      remote: caksoylar
      revision: main
      path: zmk

    - name: zmk-rgbled-widget
      url: https://github.com/t-ogura/zmk-rgbled-widget
      revision: main
      path: zmk-rgbled-widget

  self:
    path: config
