CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y

CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
# Set this to 2 + your desired number of BT profiles
CONFIG_BT_MAX_CONN=7
# Set this to the same number as BT_MAX_CONN
CONFIG_BT_MAX_PAIRED=7

# battery reporting
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
# ZMK StudioのRAW HID通信を有効化（これでUSB上にStudioの通り道が作られます）
CONFIG_ZMK_STUDIO=y



CONFIG_RGBLED_WIDGET=n
CONFIG_SMART_RGBLED_WIDGET=n