CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y

CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
# Set this to 2 + your desired number of BT profiles
CONFIG_BT_MAX_CONN=7
# Set this to the same number as BT_MAX_CONN
CONFIG_BT_MAX_PAIRED=7

# battery reporting
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
# ZMK StudioのRAW HID通信を有効化（これでUSB上にStudioの通り道が作られます）
CONFIG_ZMK_STUDIO=y


# USB Mass Storage Class (大容量記憶装置) を完全にオフにする
CONFIG_USB_DEVICE_MSC=n
CONFIG_USB_MSC=n
# 内部フラッシュのディスクマウント機能を無効化
CONFIG_IMG_MANAGER=n
