name: Build ZMK firmware
on:
  workflow_dispatch:
  push:
    paths:
    - config/west.yml
    - config/*.keymap
    - config/*.conf
    - config/includes/*.dtsi
    - boards/shields/totem/*.conf
    - boards/shields/totem/*.overlay
    - boards/shields/totem/*.dts
    - boards/shields/totem/*.dtsi
    - build.yaml

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
